### PR TITLE
Meta tag support

### PR DESCRIPTION
**Pull request by WyriHaximus**
Allow pages to set custom meta tags. The default is not to index anything but allow all links. Only pages with content should be indexed so a site doesn't pollute the search index and might be punished for it. The second thing I've added are feed tags for category and tag feeds added recently.

### CODE REVIEW

**Comment by simensen** [comment]
I like this. I've been doing this a lot myself. I've just been using block named `meta`. What do you think about that?

**Comment by WyriHaximus** [comment]
`meta` sounds good to me but the reason why I named it `metaTags` because it clarifies it's for meta tags and not other kinds of meta data.

**Comment by simensen** [comment]
OK. The things I've been doing is:

 * meta (gets injected just before the local stylesheet is included)
 * styles (gets injected just before `</head>`)
 * script (gets injected just before `</body>`)

I'd love to come up w/ something that can be more consistent. I suppose we could do `meta`, `style`, `script`, or `meta`, `styles`, `scripts`?

I also think the idea of being more specific could be helpful. Maybe `head_meta` instead of `metaTags`? So `head_meta`, `head_styles`, `scripts_after` or something?

**Comment by WyriHaximus** [comment]
`head_meta`, `head_styles`, `scripts_after` makes perfect sense because it's clear where things are going to be. Want me to extend that into this PR and update it? I might even consider adding `head_scripts` that is injected right after `head_styles` for small snippets that aren't blocking the loading of the page.

**Comment by simensen** [comment]
Yep, that sounds good to me.

**Comment by simensen** [comment]
Read: yes, if you want to make those changes and add it to this PR, that would be awesome. You can either add commits or rebase / squash. I'm fine with either.

**Comment by WyriHaximus** [comment]
It will be only 1 other commit so not rebasing or squashing so the history is clear on why the changed happened.

**Comment by simensen** [comment]
I won't get a notification when you push new code so ping the issue manually when you're ready for me to take a look again! Thanks. :)

**Comment by WyriHaximus** [comment]
Will do :).

**Comment by WyriHaximus** [comment]
*ping*

**Comment by simensen** [comment]
Thanks!

**Pull request merged**
